### ISSUE TITLE
Some proposal stages broken - "NaN"

### ISSUE THREAD

**Issue by karlhorky** [bevacqua/prop-tc39#3]
The website is showing the following at the bottom of the list:

<img width="522" alt="screen shot 2017-11-01 at 16 33 26" src="https://user-images.githubusercontent.com/1935696/32282664-80ad3e32-bf22-11e7-9dda-5bb7bdfe2c7c.png">

Some (all) of the Stage 4 and Stage 0 proposals are being displayed properly.

I guess this may have something to do with a change in format or something.

**Comment by karlhorky** [comment]
Looks like this could have been the cause: tc39/proposals#81

**Comment by t1ger-0527** [comment]
#4
